In [1]:
import pandas as pd

In [ ]:
df = pd.read_parquet("data/numerai/v5.2/validation.parquet", columns=['era', 'data_type'])

In [12]:
df.head()

                   era   data_type
id
n000101811a8a843  0575  validation
n001e1318d5072ac  0575  validation
n002a9c5ab785cbb  0575  validation
n002ccf6d0e8c5ad  0575  validation
n0041544c345c91d  0575  validation

In [14]:
df[df['data_type']=="validation"].tail()

                   era   data_type
id
nffedb55d1d2370b  1216  validation
nffeebba305a250d  1216  validation
nfff035626b996e5  1216  validation
nfff3f9abd852586  1216  validation
nfff8bace7215262  1216  validation