In [1]:
import pandas as pd

In [ ]:
old_df = pd.read_parquet("data/numerai/v5.2/validation.parquet", columns=['era', 'data_type'])
old_df[old_df['data_type']=="validation"].tail()

                   era   data_type
id
nffedb55d1d2370b  1216  validation
nffeebba305a250d  1216  validation
nfff035626b996e5  1216  validation
nfff3f9abd852586  1216  validation
nfff8bace7215262  1216  validation

In [15]:
from pathlib import Path
from numerapi import NumerAPI

# If your notebook is inside the repo, this is enough:
ROOT = Path.cwd()

# If not, uncomment and set the repo root explicitly:
# ROOT = Path(r"C:\Users\nopro\OneDrive\Desktop\numerai-mcp-autoresearch")

DATA_VERSION = "v5.2"
DATA_DIR = ROOT / "data" / "numerai" / DATA_VERSION
DATA_DIR.mkdir(parents=True, exist_ok=True)

remote = f"{DATA_VERSION}/validation.parquet"
local = DATA_DIR / "validation.parquet"

print(f"Downloading {remote} -> {local}")
napi = NumerAPI()
napi.download_dataset(remote, str(local))

print("Done.")
print(local)

Downloading v5.2/validation.parquet -> c:\Users\nopro\OneDrive\Desktop\numerai-mcp-autoresearch\data\numerai\v5.2\validation.parquet

2026-06-06 09:55:38,562 INFO numerapi.utils: target file already exists
2026-06-06 09:55:38,563 INFO numerapi.utils: resuming download
c:\Users\nopro\anaconda3\envs\numerai_rag_env\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'numerai-datasets-us-west-2.s3-us-west-2.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\nopro\OneDrive\Desktop\numerai-mcp-autoresearch\data\numerai\v5.2\validation.parquet: 4.28GB [03:37, 19.7MB/s]

Done.
c:\Users\nopro\OneDrive\Desktop\numerai-mcp-autoresearch\data\numerai\v5.2\validation.parquet

In [16]:
new_df = pd.read_parquet("data/numerai/v5.2/validation.parquet", columns=['era', 'data_type'])
new_df[new_df['data_type']=="validation"].tail()

                   era   data_type
id
nffcee43b87894fd  1217  validation
nffd051b3f88d536  1217  validation
nffd95081f080f2f  1217  validation
nffe5275006f2973  1217  validation
nffee41cfa736809  1217  validation